name: Wiki Diff
description: Get the diff of a Wiki (gollum) change
author: Lukas Gjetting

inputs:
  repoToken:
    description: Should be set to `secrets.GITHUB_TOKEN`
    required: true

outputs:
  diff:
    description: The raw diff text
  diff-slack:
    description: The formatted diff text, to be used in a Slack message

runs:
  using: node12
  main: dist/index.js