name: Test

on: [gollum]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: |
          git clone https://github.com/lukasgjetting/wiki-diff-action.wiki.git wiki
          cd wiki
          ls
          echo github.pages
          git show ${{ github.pages[0].sha }}
      - name: Checkout wiki repo
        uses: actions/checkout@v2
        with:
          repository: lukasgjetting/wiki-diff-action.wiki
          path: wiki
      - name: Test
        uses: lukasgjetting/wiki-diff-action@master
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}