name: Test

on: [gollum]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - id: first
        run: echo "::set-output name=test::hello"
      - run: echo "${{ steps.first.outputs.test }}"
      - id: git
        run: |
          git clone https://github.com/lukasgjetting/wiki-diff-action.wiki.git wiki
          cd wiki
          git log --format=%B -n 1 ${{ github.pages[0].sha }} | (echo '::set-output name=msg::' && cat) | tr -d '\n'
      - run: echo "${{ steps.git.outputs.msg }}"