name: Test

on: [push]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Test
        uses: lukasgjetting/wiki-diff-action@master
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}